### ISSUE TITLE
Please strong name the released assemblies.

### ISSUE THREAD

**Issue by niemyjski** [yadyn/WPF-Task-Dialog#1]
Please strong name the released assemblies.

**Comment by yadyn** [comment]
Any particular reason you need them to be strong named? Is this for ClickOnce signing?

You'd probably be better off downloading the source and signing it yourself with your own key, either a company, personal, or project-specific one. The license should permit this.

**Comment by niemyjski** [comment]
I will be deploying this assembly with our application. Our whole application is strong named. I can't compile our project without strong naming it. Also if you are going the nuget route, you will want to strong name it :). I pulled source and signed it with my key.

**Comment by yadyn** [comment]
Since this is a bit specific to your needs, I'm gonna close this and just suggest that anyone who needs it strongly named should download the source and build it with a key themselves as needed. Most everyone else probably won't need or care if it is strongly named.

**Comment by niemyjski** [comment]
I think it is more common for third party's to automatically strong name it. All assemblies deployed via nuget are pretty much strong named.  It also saves developers time from downloading the source.
