### ISSUE TITLE
Rename Show method to ShowDialog

### ISSUE THREAD

**Issue by niemyjski** [yadyn/WPF-Task-Dialog#10]
I added this just to be more consistent with the .NET API. The Show method displays a dialog (hence task "dialog")...

**Comment by yadyn** [comment]
I agree. There are a lot of namespace and other naming things I really want to change now, but it would incur a lot of breaking changes for folks. Thus, it'll have to wait for version 2.0 someday.

**Comment by niemyjski** [comment]
You could implement them, and have duplicates and just mark the show as deprecated (and remove them in 2.0).

**Comment by yadyn** [comment]
Good idea. I'll look into doing that then. Always forget about the Obsolete attribute!

**Comment by ygoe** [comment]
MessageBox.Show also has no "ShowDialog" and the class name "TaskDialog" already brings the "Dialog" with it. I personally wouldn't want to change the "Show" into a "ShowDialog" method here. More typing for little more use. jm2c
