### ISSUE TITLE
Nuget support

### ISSUE THREAD

**Issue by niemyjski** [yadyn/WPF-Task-Dialog#2]
Do you have any plans to add this to nuget?

**Comment by yadyn** [comment]
I have no plans but it seems like it would be a good thing to do! I've never put together a NuGet package before but it would be a good way to learn it. I'll definitely put this on the ToDo. Thanks!

**Comment by GeorgeHahn** [comment]
I was actually just looking for a TaskDialog library on NuGet and didn't find any. It'd be pretty awesome if this were available there!

**Comment by yadyn** [comment]
Okay, I toyed around with nuget.exe and the NuGet docs for a bit and managed to publish... something!

https://nuget.org/packages/WPFTaskDialog

I hope it works okay. Let me know if there are any issues with it and I'll try to fix it.

**Comment by GeorgeHahn** [comment]
Awesome! Thank you!
