### ISSUE TITLE
Support for the Vista Folder Browser

### ISSUE THREAD

**Issue by niemyjski** [yadyn/WPF-Task-Dialog#3]
If you could add support for the Vista Folder Browser that would be awesome!
http://wpffolderbrowser.codeplex.com/releases/view/82500

**Comment by yadyn** [comment]
It's a separate project entirely and a separate use case entirely... there is no overlap in the Win32 for either, so I'm not sure what you mean by "add support"..? Seems like if you want both you just add two DLLs and use the appropriate classes as needed. Am I missing something?

**Comment by niemyjski** [comment]
It's hard to come across a pure wpf solution. I'd like to manage one external reference instead of many when it pertains to libraries that use native code for windows 7/vista features

**Comment by niemyjski** [comment]
I can put this in my fork if you would like. I just quickly did a minimal source import into your library and cleaned some things up and renamed the dialog...

**Comment by yadyn** [comment]
I'm hesitant to introduce any scope creep for this project. If anyone wants to bolt this onto their own project so they can have a single external reference, I suppose they can just add the source files themselves. But I don't think I'll be adding anything else (outside of the native Task Dialog) to it for now.

**Comment by niemyjski** [comment]
This is what I did (source import) and got it to work (just makes it a pain if you were to put this on nuget).
