### ISSUE TITLE
Callback data isn't populated after TaskDialog.Show()

### ISSUE THREAD

**Issue by niemyjski** [yadyn/WPF-Task-Dialog#8]
When I was first playing around with the sample code, I noticed that the callback data that is is passed into the callback is only the value that was populated on the options when you pass it into Show(). This is a read / write property and I was thinking that if I updated the options.Callback reference, it would be passed back to my callback (crazy thinking on my part??).

**Comment by yadyn** [comment]
There might be a way to finagle this with the emulated dialog, but the native won't do it I don't think. Once the dialog is shown, the config struct has already been passed in and read when the dialog was created. It doesn't support changing the config after the dialog is already shown. The callback lets you do some actions, however, that seem like config changes (such as renaming the caption title, etc.) but really they aren't. They are rewriting the window values directly in most cases, not changing the config struct.

Your best bet might just be to pass in some kind of reference object instead as your CallbackData. Value types will be forever static. Usually, this value is to help distinguish things. You can have one callback handler method and use the callback data to help you know which dialog is calling back, should you ever have potentially more than one shown at a time. I believe it is similar in practice to the IAsyncResult's AsyncState value when using oldskool delegates and Invoke.

**Comment by niemyjski** [comment]
Can we then make these properties be read only or throw an exception if the property is modified after the dialog is shown(the first option is better).. This would make it much clearer to the developer using the libraries. If you could add a sample of this, it would be appreciated.

**Comment by yadyn** [comment]
I'm not sure how I would make it read-only. It needs to be writable on the config struct you pass into `Show`. After that, in your callback handler it's typical that you don't expect modifications to local parameters to propagate beyond the scope of your method. Seems like you would only expect it is writable if its passed with `ref` or `out` or something.

**Comment by niemyjski** [comment]
You can have a flag and then check it in the property setter and throw an exception.
