### ISSUE TITLE
Ability to close a dialog from within a callback.

### ISSUE THREAD

**Issue by niemyjski** [yadyn/WPF-Task-Dialog#9]
I really had to do some playing around to get this to work. Basically, when my file gets done extracting, I want to auto close the dialog and not wait for the user to click close (or in my case no button). I wish there was a way to expose explicit behavior like close the dialog from within the callback.

what I did was simulate a button click like this in my samples callback.
if (_extractionComplete) {
                var dialog = d as TaskDialogViewModel;
                if (dialog != null) {
                    dialog.NormalButtonCommand.Execute(0); // Simulate a button click, which calls the callback again.
                    return false;
                }
            }

Also, I wish the callback had a callback event args and my callback had a void method signature. The callback could have the callback data on it, the notification type and the associated dialog. I could then do like a args.Cancel = true (like wpf commands) and it would be more readable then returning true or false.

Sorry for hammering you with issues. I really like the lib and it's the best one I've come across so far :).

**Comment by yadyn** [comment]
Someone else had this [exact request](http://www.codeproject.com/Messages/4289088/Closing-the-dialog-from-the-callback.aspx) on the CodeProject article for this project.

Seems like the best alternative is to use ClickButton to simulate a click on a known Close button. The native Task Dialog doesn't have any CloseDialog feature that I am aware of.

Unfortunately, I'll need to add support for ClickButton to the ViewModel emulator class before I can add it to the IActiveTaskDialog interface.

**Comment by yadyn** [comment]
I agree about the callback signature. Using args.Cancel would be more .NET-like, but it goes against how the native callback expects things. Right now they interpret that boolean return value based on the notification type. Cancel would only (sort of) make sense during a ButtonClicked callback notification. On all others it wouldn't apply and wouldn't make sense. Also, for each notification type that needed interaction values (like Timer) we'd have to add another boolean onto the args just for that notification type. It would get confusingly messy, I think. Oh well.

**Comment by yadyn** [comment]
I've added support for ClickButton into the interface and ViewModel directly in the latest check-in. As stated in the check-in comments, I've also updated the sample application to show closing a progress dialog automatically when it completes using the ClickButton method in a callback.

**Comment by niemyjski** [comment]
Thank you so much! 
Since this is a .NET wrapper around native code, it makes sense to have .NET like api (args.Cancel).
